config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "buddies#index"
  resources :buddies, only: %i[index show edit update] do
    member do
      get :profil, as: "profil"
    end
  end
  resources :prestations, only: %i[show index] do
    resources :bookings, only: %i[index new create edit update]
    get 'user_prestations'
  end
  resources :bookings, except: %i[index new create]

  namespace :admin do
    resources :bookings, only: %i[index update]
    resources :prestations
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :prestation

  enum :validation, pending: 0, validated: 1, refused: 2
  validates :date, presence: true
end

app/models/prestation.rb
class Prestation < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :price, presence: true, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { in: 0..1_000_000 }
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 20, message: 'make a longer description biatch' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :prestations, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :email, presence: true
  validates :name, uniqueness: true, presence: true
  validates :description, presence: true, length: { minimum: 20, message: 'make a longer description biatch' }
end

app/controllers/admin/bookings_controller.rb
class Admin::BookingsController < ApplicationController
  before_action :set_booking, only: :update

  def index
    @bookings = current_user.bookings
    @pendings = Booking.where(validation: 0)
    @validates = Booking.where(validation: 1)
    @refuseds = Booking.where(validation: 2)
  end

  def update
    if params[:validation] == "1"
      @booking.validation = "validated"
    else
      @booking.validation = "refused"
    end
    if @booking.update(validation: @booking.validation)
      redirect_to admin_bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/admin/prestations_controller.rb
class Admin::PrestationsController < ApplicationController
  def index
    @prestations = current_user.prestations
  end

  def new
    @prestation = Prestation.new
  end

  def create
    @prestation = Prestation.new(prestation_params)
    @prestation.user = current_user
    if @prestation.save
      redirect_to admin_prestation_path(@prestation)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @prestation = Prestation.find(params[:id])
  end

  def edit
    @prestation = Prestation.find(params[:id])
  end

  def update
    @prestation = Prestation.find(params[:id])
    @prestation.update(prestation_params)
    redirect_to admin_prestation_path(@prestation)
  end

  def destroy
    @prestation = Prestation.find(params[:id])
    @prestation.destroy
    redirect_to admin_prestation_path
  end

  private

  def prestation_params
    params.require(:prestation).permit(:name, :description, :price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :description])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :description])
  end

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_presta, except: %i[ destroy]
  before_action :set_booking, only: %i[show edit update destroy]

  def index
    @bookings = current_user.bookings
  end

  def new
    @prestation = Prestation.find(params[:prestation_id])
    @booking = Booking.new
  end

  def create
    @prestation = Prestation.find(params[:prestation_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.prestation = @prestation
    if @booking.save
      redirect_to prestation_bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    @prestation = @booking.prestation
    if @booking.update(booking_params)
      redirect_to prestation_bookings_path(@prestation)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @prestation = @booking.prestation
    @booking.destroy
    redirect_to prestation_bookings_path(@prestation)
  end

  private

  def set_presta
    @prestation = Prestation.find(params[:prestation_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:date, :validation)
  end
end

app/controllers/buddies_controller.rb
class BuddiesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_buddy, only: %i[show profil update]

  def index
    @prestations = Prestation.all
    @buddies = User.all
  end

  def show
    @booking = Booking.new
    @prestations = Prestation.all
  end

  def edit
    @buddy = User.find(params[:id])
  end

  def update

    @buddy.update(buddy_params)
    redirect_to buddy_path(@buddy)

  end

  def profil
    @prestations = Prestation.all
  end

  private

  def buddy_params
    params.require(:user).permit(:name, :mail, :description, :photo)
  end

  def set_buddy
    @buddy = User.find(params[:id])
  end

end

app/controllers/clients/bookings_controller.rb
class Clients::BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def edit
  end

  def update
  end
end

app/controllers/prestations_controller.rb
class PrestationsController < ApplicationController
  def index
    @prestations = Prestation.all
  end

  def show
    @prestation = Prestation.find(params[:id])
  end

  def user_prestations
    @prestations = Prestation.where(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_list, only: :show

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
  end

  private

  def user_params
    params.require(:user).permit(:name, :mail, :description, :photo)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/bookings/index.html.erb
<h1>Valider mes demandes de prestations</h1>
<div class="container py-5">
  <div class="row">
    <div class="booking-reservations">
      <div class="bg-white rounded p-3 shadow">
        <h4>Liste de toutes les demandes de prestations en attentes de validation</h4>
        <div class="group-resa">
        <% @pendings.each do |pending| %>
        <div class="validation">
          <div class="validation-btn">
            Date : <strong><%=  pending.date %></strong>  --  Prix : <strong> <%=  pending.prestation.price %></strong> €
          </div>
          <div class="validation-btn">
            <%= link_to "Valider", admin_booking_path(pending, validation: 1), data: { turbo_method: :patch }, class: "btn btn-outline-success btn-sm" %>
            <%= link_to "Refuser", admin_booking_path(pending, validation: 2), data: { turbo_method: :patch }, class: "btn btn-outline-danger btn-sm" %>
          </div>
          </div>
        <% end %>
        </div>
      </div>
    </div>
    <div class="booking-reservations">
      <div class="bg-white rounded p-3 shadow">
        <h4>Liste de toutes les demandes de prestations validée</h4>
        <div class="group-resa">
          <% @validates.each do |validate| %>
          <div class="validation">
            <div class="validation-btn">
              Date : <strong><%=  validate.date %></strong>  --  Prix : <strong> <%=  validate.prestation.price %></strong> €
            </div>
          </div>
        <% end %>
        </div>
      </div>
    </div>
    <div class="booking-reservations">
        <div class="bg-white rounded p-3 shadow">
          <h4>Liste de toutes les demandes de prestations refusées</h4>
          <div class="group-resa">
            <% @refuseds.each do |refused| %>
            <div class="validation">
              <div class="validation-btn">
                Date : <strong><%=  refused.date %></strong>  --  Prix : <strong> <%=  refused.prestation.price %></strong> €
              </div>
            </div>
          <% end %>
          </div>
        </div>
      </div>
  </div>
</div>

<%# validation = pending %>








<%# <h3>Liste de toutes les prestations terminées (optionnel)</h3>
<%# validation = closed %>
<%# @bookings.each do |booking| %>
<%#=  booking.date %><%#=  booking.prestation.price %>
<%# end %>

app/views/admin/prestations/edit.html.erb
<h1>Modifier ma prestation</h1>
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3><%= @prestation.name %></h3>
        <%= simple_form_for [:admin, @prestation] do |f| %>
          <%= f.input :name, placeholder: 'Prestation name' %>
          <%= f.input :description, placeholder: 'Description' %>
          <%= f.input :price, placeholder: '$$$' %>
          <%= f.submit class: 'btn btn-flat' %>
          <%= link_to  "<- Retour", admin_prestations_path%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/prestations/index.html.erb
<div class="prestations-container">
  <div class="titre-page-admin">
    <h1>Liste de mes prestations</h1>
  </div>
  <div class="cards-product">
    <% @prestations.each do |presta| %>
      <div class="card-product">
        <img src="https://picsum.photos/200" />
        <div class="card-product-infos">
          <h3 style= "color:rgb(24, 49, 83)"><%= link_to presta.name, admin_prestation_path(presta), class:"text-decoration-none" %></h3>
          <p><%= presta.description  %></p>
          <p><%= presta.price %>€</p>
          <%= link_to edit_admin_prestation_path(presta) do%>
              <i class="fa-solid fa-pen"></i>
          <% end %>
        </div>
        <%= link_to admin_prestation_path(presta), data: {turbo_method: :delete, turbo_confirm: "est-tu sûr Maggle?"} do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="container">
    <%= link_to new_admin_prestation_path(@prestation) do %>
      <i class="fa-solid fa-square-plus"></i>
    <% end %>
  </div>
</div>

app/views/admin/prestations/new.html.erb
<h1>Nouvelle prestation</h1>
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Creer une nouvelle prestation</h3>
        <%= simple_form_for [:admin, @prestation] do |f| %>
          <%= f.input :name, placeholder: 'Name' %>
          <%= f.input :description, placeholder: 'Description' %>
          <%= f.input :price, placeholder: '$$$' %>
          <%= f.submit class: 'btn btn-flat' %>
          <%= link_to  "<- Retour>", admin_prestations_path%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/prestations/show.html.erb
<h1>Prestation</h1>
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <%= link_to  "<- Retour", admin_prestations_path%>
        <h2><%= @prestation.name %></h2>
        <h3>Description</h3>
        <p><%= @prestation.description %></p>
        <br>
        <p>Prix de la prestation (par jour) : <%= @prestation.price %>€</p>
      </div>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<h1>Modifier ma reservation</h1>
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h2>Changez la date de votre reservation :</h2>
        <%= simple_form_for [@prestation, @booking], method: :patch  do |f| %>
          <%= f.input :date, as: :date, html5: true %>
          <%= f.submit class: "btn btn-primary" %>
        <% end %>
        <%= link_to '<- Retour', prestation_bookings_path(@prestation) %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<h1>Liste de mes demandes de reservations</h1>
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <p>Vous voulez reserver cette prestation sur d'autres jours ? C'est par <%= link_to 'ici', new_prestation_booking_path %> </p>
        Prestation est prévue pour le :
        <ul>
        <% @bookings.each do |booking| %>
          <li>
          -- <%= booking.date %> -- <br>
          <%= link_to 'Voir les details', booking_path(id: booking.id, prestation_id: booking.prestation.id) %> --
          <%= link_to "Modifier", edit_booking_path(id: booking.id, prestation_id: booking.prestation.id) %> --
          <%= link_to "Supprimer", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Tu es sûr?" } %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<h1>Nouvelle reservation</h1>
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h2>Indiquez la date de votre reservation :</h2>
        <%= simple_form_for [@prestation, @booking], method: :create  do |f| %>
          <%= f.input :date, as: :date, html5: true %>
          <%= f.submit class: "btn btn-primary" %>
        <% end %>
        <%= link_to '<- Revenir à la liste des prestations', prestation_bookings_path %>
        </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Details de votre reservation</h1>
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        Vous avez reservé la prestation : <br>
        <h4><%= @booking.prestation.name %></h4>
        Realisée par : <br>
        <h5><%= @booking.prestation.user.name %></h5>
        Pour la date du :<br>
        <strong><%= @booking.date %></strong><br>
        <%= link_to '<- Retour', prestation_bookings_path(@prestation) %>
      </div>
    </div>
  </div>
</div>

app/views/buddies/edit.html.erb
<h1>Modifier mon profil</h1>
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <%= form_for(@buddy, url: buddy_path(@buddy), html: {method: :put}) do |f| %>
          <%= f.text_field :name, placeholder: @buddy.name  %>
          <%= f.text_field :description %>
          <%= f.submit %>
        <% end %>
        <%= link_to '<- Retour', profil_buddy_path(current_user) %>
      </div>
    </div>
  </div>
</div>

app/views/buddies/index.html.erb
<div class="container" >
  <div class="card-category-bar">
    <div class="icones">
      <div class="icones1">
        <i class="fa-solid fa-person-rifle"></i>
        <div class="texte-taille">
        <p>Assassin</p>
        </div>
      </div>

      <div class="icones1">
      <i class="fa-solid fa-kit-medical"></i>
        <div class="texte-taille">
        <p>Soin</p>
        </div>
      </div>

      <div class="icones1">
      <i class="fa-solid fa-user-ninja"></i>
        <div class="texte-taille">
          <p>Ninja</p>
        </div>
      </div>

      <div class="icones1">
        <i class="fa-solid fa-shield-halved"></i>
        <div class="texte-taille">
          <p>Protection</p>
        </div>
      </div>

      <div class="icones1">
        <i class="fa-solid fa-brain"></i>
        <div class="texte-taille">
        <p>Intelligence</p>
        </div>
      </div>

      <div class="icones1">
        <i class="fa-sharp fa-solid fa-hat-wizard"></i>
        <div class="texte-taille">
        <p>Mage</p>
        </div>
      </div>

      <div class="icones1">
      <i class="fa-solid fa-paw"></i>
        <div class="texte-taille">
        <p>Animal</p>
        </div>
      </div>

      <div class="icones1">
      <i class="fa-solid fa-flask"></i>
        <div class="texte-taille">
        <p>Alchimie</p>
        </div>
      </div>

      <div class="icones1">
      <i class="fa-solid fa-utensils"></i>
        <div class="texte-taille">
        <p>Nourriture</p>
        </div>
      </div>

      <div class="icones1">
      <i class="fa-solid fa-circle-info"></i>
        <div class="texte-taille">
        <p>More</p>
        </div>
      </div>
    </div>
  </div>

  <div class="cards">
    <% @buddies.each do |buddy|%>
    <div class="card-trip">
      <img src="https://www.leparisien.fr/resizer/Zd5d8PUSgMW-RzntrZ8iAJhunEM=/arc-anglerfish-eu-central-1-prod-leparisien/public/XCBSBSI3XZHYRMALPNPRH54ULM.jpg" />
      <div class="card-trip-infos">
        <div>
          <div class="btn btn-">
            <h2><%= link_to buddy.name, buddy_path(buddy)%></h2>
          </div>
          <p><%= buddy.description %></p>
        </div>
        <h2 class="card-trip-pricing"> </h2>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/buddies/profil.html.erb
<div class="container">
    <div class="cards">
      <div class="card-category" style="background-image: url(<%= image_path "profil-carac.png" %>)">
        <div class="buddy-caractéristiques">
          <h1><%=  %></h1>
        </div>
      </div>
      <div class="card-category-mid">
        <div class="buddy-name">
          <%= @buddy.name %><br>
          <div class="buddy-avatar">
            <div class="avatar-img" style="background-image:  url(https://media.vogue.fr/photos/621f567e42cb113ca47921d9/2:3/w_2560%2Cc_limit/MCDBATM_WB060.jpg)">
            </div>
          </div>
        </div>
      </div>
      <div class="card-category-btn">
          <div class="boutons-params">
            <%= link_to 'Ajouter une prestation', new_admin_prestation_path(@prestation), class: "btn btn-primary"%>
          </div>
          <div class="boutons-params">
            <%= link_to "Modifier mon profil", edit_buddy_path(@buddy), class: "btn btn-primary"  %>
            </div>
          <div class="boutons-params">
            <%= link_to "Back to buddies list MF", buddies_path(@buddy), class: "btn btn-primary" %>
            </div>
          <div class="boutons-params">
            <%= link_to "Mes prestas admin", admin_prestations_path, class: "btn btn-primary" %>
            </div>
          <div class="boutons-params">
            <%= link_to "Historique des reservations", admin_bookings_path(@buddy), class: "btn btn-primary" %>
            </div>
          </div>
      </div>
    </div>
    <div class="card-positionner">
        <div class="card-category-description">
          <div class="description">
              <p>Description</p>
            <p><%= @buddy.description %></p>
        </div>
      </div>
    </div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>





    <div class="cards-product">
    <% @prestations.each do |presta| %>
      <div class="card-product">
        <img src="https://picsum.photos/200" />
        <div class="card-product-infos">
          <h3 style= "color:rgb(24, 49, 83)"><%= link_to presta.name, admin_prestation_path(presta), class:"text-decoration-none" %></h3>
          <p><%= presta.description  %></p>
          <p><%= presta.price %>€</p>
          <%= link_to edit_admin_prestation_path(presta) do%>
              <i class="fa-solid fa-pen"></i>
          <% end %>
        </div>
        <%= link_to admin_prestation_path(presta), data: {turbo_method: :delete, turbo_confirm: "Es-tu sûr Biatch?"} do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      </div>
    <% end %>
</div>

app/views/buddies/show.html.erb
<h1><%= @buddy.name  %></h1>
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <p>Description :<br>
        <%= @buddy.description %></p>
        <ul>
          <% @prestations.each do |prestation| %>
            <li><strong><%= prestation.name %></strong><br>
              Description :<br>
              <%=  prestation.description %><br>
              Prix : <%=  prestation.price %>€ <br>
              <%= link_to "Je reserve cette prestation", new_prestation_booking_path(prestation), class: "btn btn-warning" %> <br><br>
            </li>
          <% end %>
        </ul>

        <%= link_to "Retour à la liste des Buddies", buddies_path(@buddy), class: "btn btn-primary" %>
        <%= link_to "Modifier mon profil", edit_buddy_path(@buddy), class: "btn btn-warning" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PowerUp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/prestations/_form.html.erb
<div class="form-inputs">
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
</div>

app/views/prestations/index.html.erb
<div class="prestations-container">
  <h1 class="titre-page">Liste de mes prestations</h1>
  <div class="cards-product">
    <% @prestations.each do |presta| %>
      <div class="card-product">
        <img src="https://picsum.photos/200" />
        <div class="card-product-infos">
          <h3 style= "color:rgb(24, 49, 83)"><%= link_to presta.name, admin_prestation_path(presta), class:"titre-presta" %></h3>
          <p><%= presta.description  %></p>
            <div class="price-product"><%= presta.price %>€</p></div>
          <div>
            <%= link_to "Réserver maintenant", new_prestation_booking_path(presta), class:"bouton-reservation" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="container">
  </div>
</div>

app/views/prestations/show.html.erb
<div class="prestations-container">
  <h1 class="titre-page">Prestations</h1>
  <div class="cards-product">
      <div class="card-product">
        <img src="https://picsum.photos/200" />
        <div class="card-product-infos">
          <h3 style= "color:rgb(24, 49, 83)"><%= link_to presta.name, admin_prestation_path(presta), class:"titre-presta" %></h3>
          <p><%= presta.description  %></p>
          <p><%= presta.price %>€</p>
          <div>
          <%= link_to  "retour", prestations_path%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to buddies_path(@buddy), class: "navbar-brand" do %>
      <%= image_tag "https://www.dlf.pt/dfpng/middlepng/257-2579383_circle-icons-bolt-flat-power-up-icon-hd.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <%# <%= cl_image_tag("PHILIPPE-ETCHEBEST-e1606153576338_uoanmf", crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profil", profil_buddy_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete},
  class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>